name: Deploy to AWS EC2
on:
  push:
    paths:
      - api/**
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
            context: "{{defaultContext}}:api"
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/quoteversation:latest

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop quoteversation || true
            docker rm quoteversation || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/quoteversation:latest
            docker run -d -p 5121:5121 --env-file .env --name quoteversation ajambot/quoteversation:latest